name: moor_generator
description: Dev-dependency to generate table and dataclasses together with the moor package.
version: 4.6.0
repository: https://github.com/simolus3/moor
homepage: https://moor.simonbinder.eu/
issue_tracker: https://github.com/simolus3/moor/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.1.0
  drift_dev: ^1.0.0
  # When users depend on the latest moor_generator, they should also get the latest moor for
  # the migration to work
  moor:
    git:
      url: "https://github.com/thachnb85/moor.git"
      path: moor

executables:
  moor_generator:

dependency_overrides:
  drift:
    path: ../drift
  drift_dev:
    path: ../drift_dev
  sqlparser:
    path: ../sqlparser
  moor:
    path: ../moor
