name: flutter_db
description: Moor integration tests running on sqflite
version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  tests:
    path: ../tests
  sqlite3_flutter_libs: ^0.2.0

dev_dependencies:
  test:

dependency_overrides:
  drift:
    path: ../../../drift
  moor_flutter:
    path: ../../../moor_flutter
  moor:
    path: ../../../moor

flutter:
  assets:
    - test_asset.db