LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

sqlite_flags := \
     -DSQLITE_DQS=0 \
     -DSQLITE_THREADSAFE=0 \
     -DSQLITE_DEFAULT_MEMSTATUS=0 \
     -DSQLITE_MAX_EXPR_DEPTH=0 \
     -DSQLITE_OMIT_AUTHORIZATION \
     -DSQLITE_OMIT_DECLTYPE \
     -DSQLITE_OMIT_DEPRECATED \
     -DSQLITE_OMIT_GET_TABLE \
     -DSQLITE_OMIT_LOAD_EXTENSION \
     -DSQLITE_OMIT_PROGRESS_CALLBACK \
     -DSQLITE_OMIT_SHARED_CACHE \
     -DSQLITE_OMIT_TCL_VARIABLE \
     -DSQLITE_OMIT_TRACE \
     -DSQLITE_USE_ALLOCA \
     -DSQLITE_UNTESTABLE \
     -DSQLITE_HAVE_ISNAN \
     -DSQLITE_ENABLE_FTS5 \
     -DSQLITE_ENABLE_JSON1 \
     -O3

LOCAL_CFLAGS += $(sqlite_flags)

ifeq ($(TARGET_ARCH), arm)
	LOCAL_CFLAGS += -DPACKED="__attribute__ ((packed))"
else
	LOCAL_CFLAGS += -DPACKED=""
endif

LOCAL_SRC_FILES = sqlite3.c
LOCAL_MODULE = libsqlite3

include $(BUILD_SHARED_LIBRARY)